CREATE TABLE `broker_connections` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`brokerType` enum('alpaca','interactive_brokers','binance','coinbase') NOT NULL,
	`isPaper` boolean NOT NULL DEFAULT true,
	`isActive` boolean NOT NULL DEFAULT true,
	`accessTokenEncrypted` text,
	`refreshTokenEncrypted` text,
	`accessTokenSecretEncrypted` text,
	`tokenExpiresAt` timestamp,
	`liveSessionTokenEncrypted` text,
	`liveSessionTokenExpiresAt` timestamp,
	`accountId` varchar(128),
	`accountNumber` varchar(64),
	`accountType` varchar(32),
	`lastConnectedAt` timestamp,
	`lastSyncAt` timestamp,
	`connectionError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `broker_connections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `broker_orders` (
	`id` varchar(64) NOT NULL,
	`connectionId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`brokerOrderId` varchar(128),
	`clientOrderId` varchar(128),
	`symbol` varchar(32) NOT NULL,
	`side` enum('buy','sell') NOT NULL,
	`orderType` enum('market','limit','stop','stop_limit','trailing_stop') NOT NULL,
	`timeInForce` enum('day','gtc','ioc','fok','opg','cls') NOT NULL DEFAULT 'day',
	`quantity` decimal(18,8) NOT NULL,
	`price` decimal(18,8),
	`stopPrice` decimal(18,8),
	`trailPercent` decimal(8,4),
	`filledQuantity` decimal(18,8) NOT NULL DEFAULT '0',
	`avgFillPrice` decimal(18,8),
	`status` enum('new','pending','accepted','partially_filled','filled','cancelled','rejected','expired','replaced') NOT NULL DEFAULT 'new',
	`extendedHours` boolean NOT NULL DEFAULT false,
	`filledAt` timestamp,
	`cancelledAt` timestamp,
	`expiredAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `broker_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `broker_positions` (
	`id` varchar(64) NOT NULL,
	`connectionId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`quantity` decimal(18,8) NOT NULL,
	`side` enum('long','short') NOT NULL,
	`avgEntryPrice` decimal(18,8) NOT NULL,
	`marketValue` decimal(18,8),
	`costBasis` decimal(18,8),
	`unrealizedPL` decimal(18,8),
	`unrealizedPLPercent` decimal(8,4),
	`currentPrice` decimal(18,8),
	`lastSyncAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `broker_positions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `oauth_states` (
	`id` varchar(64) NOT NULL,
	`state` varchar(128) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`brokerType` enum('alpaca','interactive_brokers','binance','coinbase') NOT NULL,
	`isPaper` boolean NOT NULL DEFAULT true,
	`codeVerifier` varchar(128),
	`requestToken` varchar(256),
	`requestTokenSecret` varchar(256),
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `oauth_states_id` PRIMARY KEY(`id`),
	CONSTRAINT `oauth_states_state_unique` UNIQUE(`state`)
);
