CREATE TABLE `broker_account_snapshots` (
	`id` varchar(64) NOT NULL,
	`connectionId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`equity` decimal(18,2) NOT NULL,
	`cash` decimal(18,2) NOT NULL,
	`buyingPower` decimal(18,2) NOT NULL,
	`portfolioValue` decimal(18,2) NOT NULL,
	`marginUsed` decimal(18,2) NOT NULL DEFAULT '0',
	`marginAvailable` decimal(18,2),
	`marginUtilization` decimal(8,4),
	`dayPL` decimal(18,2) NOT NULL DEFAULT '0',
	`dayPLPercent` decimal(8,4),
	`totalPL` decimal(18,2) NOT NULL DEFAULT '0',
	`totalPLPercent` decimal(8,4),
	`tradesCount` int NOT NULL DEFAULT 0,
	`winningTrades` int NOT NULL DEFAULT 0,
	`losingTrades` int NOT NULL DEFAULT 0,
	`tradingVolume` decimal(18,2) NOT NULL DEFAULT '0',
	`positionsCount` int NOT NULL DEFAULT 0,
	`longPositions` int NOT NULL DEFAULT 0,
	`shortPositions` int NOT NULL DEFAULT 0,
	`snapshotDate` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `broker_account_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `broker_performance_metrics` (
	`id` varchar(64) NOT NULL,
	`connectionId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`periodType` enum('daily','weekly','monthly','yearly','all_time') NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalReturn` decimal(18,2) NOT NULL DEFAULT '0',
	`totalReturnPercent` decimal(8,4),
	`sharpeRatio` decimal(8,4),
	`sortinoRatio` decimal(8,4),
	`maxDrawdown` decimal(8,4),
	`maxDrawdownDuration` int,
	`volatility` decimal(8,4),
	`totalTrades` int NOT NULL DEFAULT 0,
	`winningTrades` int NOT NULL DEFAULT 0,
	`losingTrades` int NOT NULL DEFAULT 0,
	`winRate` decimal(5,2),
	`profitFactor` decimal(8,4),
	`avgWin` decimal(18,2),
	`avgLoss` decimal(18,2),
	`largestWin` decimal(18,2),
	`largestLoss` decimal(18,2),
	`totalVolume` decimal(18,2) NOT NULL DEFAULT '0',
	`avgTradeSize` decimal(18,2),
	`avgHoldingPeriod` decimal(8,2),
	`calculatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `broker_performance_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `order_executions` (
	`id` varchar(64) NOT NULL,
	`orderId` varchar(64) NOT NULL,
	`connectionId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`side` enum('buy','sell') NOT NULL,
	`orderType` varchar(32) NOT NULL,
	`executionId` varchar(128),
	`executedQuantity` decimal(18,8) NOT NULL,
	`executedPrice` decimal(18,8) NOT NULL,
	`executionValue` decimal(18,2) NOT NULL,
	`commission` decimal(18,4) NOT NULL DEFAULT '0',
	`fees` decimal(18,4) NOT NULL DEFAULT '0',
	`totalCost` decimal(18,2) NOT NULL,
	`isClosingTrade` boolean NOT NULL DEFAULT false,
	`openingExecutionId` varchar(64),
	`realizedPL` decimal(18,2),
	`realizedPLPercent` decimal(8,4),
	`holdingPeriodDays` int,
	`marketPrice` decimal(18,8),
	`slippage` decimal(8,4),
	`executedAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `order_executions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portfolio_allocations` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`targetAllocations` json NOT NULL,
	`rebalanceThreshold` decimal(5,2) NOT NULL DEFAULT '5.00',
	`rebalanceFrequency` enum('manual','daily','weekly','monthly','quarterly') NOT NULL DEFAULT 'manual',
	`lastRebalancedAt` timestamp,
	`nextRebalanceAt` timestamp,
	`preferredBrokers` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `portfolio_allocations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rebalancing_history` (
	`id` varchar(64) NOT NULL,
	`allocationId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`preAllocations` json NOT NULL,
	`totalPortfolioValue` decimal(18,2) NOT NULL,
	`tradesExecuted` json NOT NULL,
	`tradesCount` int NOT NULL DEFAULT 0,
	`totalTradingVolume` decimal(18,2) NOT NULL DEFAULT '0',
	`totalFees` decimal(18,4) NOT NULL DEFAULT '0',
	`postAllocations` json NOT NULL,
	`status` enum('pending','in_progress','completed','partial','failed','cancelled') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`triggeredBy` enum('manual','scheduled','threshold') NOT NULL DEFAULT 'manual',
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rebalancing_history_id` PRIMARY KEY(`id`)
);
