CREATE TABLE `user_llm_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`activeProvider` enum('openai','deepseek','claude','gemini') NOT NULL DEFAULT 'openai',
	`openaiApiKey` text,
	`deepseekApiKey` text,
	`claudeApiKey` text,
	`geminiApiKey` text,
	`openaiModel` varchar(100) DEFAULT 'gpt-4-turbo',
	`deepseekModel` varchar(100) DEFAULT 'deepseek-reasoner',
	`claudeModel` varchar(100) DEFAULT 'claude-sonnet-4-20250514',
	`geminiModel` varchar(100) DEFAULT 'gemini-2.0-flash',
	`temperature` decimal(3,2) DEFAULT '0.7',
	`maxTokens` int DEFAULT 4096,
	`totalTokensUsed` int DEFAULT 0,
	`lastUsedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_llm_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_llm_settings_userId_unique` UNIQUE(`userId`)
);
