CREATE TABLE `agent_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentType` varchar(50) NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalSignals` int NOT NULL DEFAULT 0,
	`correctSignals` int NOT NULL DEFAULT 0,
	`accuracy` decimal(5,4),
	`bullishAccuracy` decimal(5,4),
	`bearishAccuracy` decimal(5,4),
	`neutralAccuracy` decimal(5,4),
	`marketCondition` enum('bull','bear','sideways','volatile'),
	`conditionAccuracy` decimal(5,4),
	`recommendedWeight` decimal(5,4),
	`currentWeight` decimal(5,4),
	`avgConfidence` decimal(5,2),
	`avgReturnWhenCorrect` decimal(10,4),
	`avgReturnWhenWrong` decimal(10,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `agent_performance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `earnings_call_transcripts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ticker` varchar(20) NOT NULL,
	`companyName` varchar(255),
	`callDate` timestamp NOT NULL,
	`fiscalQuarter` varchar(10),
	`fiscalYear` int,
	`callType` enum('earnings','guidance','analyst_day','special') DEFAULT 'earnings',
	`fullTranscript` text,
	`preparedRemarks` text,
	`qaSection` text,
	`participants` json,
	`overallSentiment` decimal(5,4),
	`managementTone` decimal(5,4),
	`analystTone` decimal(5,4),
	`sentimentBreakdown` json,
	`keyPhrases` json,
	`forwardGuidance` json,
	`riskMentions` json,
	`metricsDiscussed` json,
	`sourceUrl` varchar(500),
	`sourceProvider` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `earnings_call_transcripts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `earnings_sentiment_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ticker` varchar(20) NOT NULL,
	`transcriptId` int NOT NULL,
	`sentimentScore` decimal(5,4) NOT NULL,
	`confidenceScore` decimal(5,4),
	`sentimentChange` decimal(5,4),
	`trendDirection` enum('improving','declining','stable'),
	`priceAtCall` decimal(18,4),
	`priceAfter1Day` decimal(18,4),
	`priceAfter1Week` decimal(18,4),
	`priceAfter1Month` decimal(18,4),
	`signalGenerated` enum('bullish','bearish','neutral'),
	`signalAccuracy` boolean,
	`callDate` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `earnings_sentiment_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `investment_theses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`ticker` varchar(20) NOT NULL,
	`rating` enum('strong_buy','buy','hold','sell','strong_sell') NOT NULL,
	`convictionScore` decimal(5,2) NOT NULL,
	`targetPrice` decimal(18,4),
	`targetDate` timestamp,
	`timeHorizon` enum('short','medium','long') DEFAULT 'medium',
	`entryPrice` decimal(18,4) NOT NULL,
	`agentSignals` json NOT NULL,
	`consensusDetails` json,
	`executiveSummary` text,
	`fullThesis` text,
	`riskFactors` json,
	`counterThesis` text,
	`status` enum('pending','approved','rejected','closed') NOT NULL DEFAULT 'pending',
	`approvedAt` timestamp,
	`closedAt` timestamp,
	`closeReason` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `investment_theses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `thesis_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`thesisId` int NOT NULL,
	`snapshotDate` timestamp NOT NULL,
	`currentPrice` decimal(18,4) NOT NULL,
	`absoluteReturn` decimal(18,4),
	`percentReturn` decimal(10,4),
	`benchmarkReturn` decimal(10,4),
	`alphaGenerated` decimal(10,4),
	`targetProgress` decimal(10,4),
	`maxDrawdown` decimal(10,4),
	`volatility` decimal(10,4),
	`sharpeRatio` decimal(10,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `thesis_performance_id` PRIMARY KEY(`id`)
);
